# Generated by Django 4.1.1 on 2022-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='danger',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
